Maybe solved issue 80
uqbar-project/wollok-ts pull request #86
Opened 2021-06-24 00:34 UTC by AngeliMatias

Fix #80 

Por ahora está funcionando, probablemente se puede optimizar. No utilizamos yield y la llamada a la función que estamos usando quizás podría estar afuera, pero no quisimos ensuciar mucho la interfaz en sí del programa.

2021-06-29 14:13 UTC, PalumboN commented on src/wre/game.ts
> +      }
Esto podría sacarse fuera, en dos funciones separadas del método.

2021-06-29 14:13 UTC, PalumboN approved these changes

2021-07-23 19:46 UTC, ezequielPereyra commented
Creo que ahí quedó. Aunque acá también se pide el atributo position del objeto. Tendremos que cambiarlo una vez terminemos de deprecar los métodos `addVisualIn` y `addVisualCharacterIn`.

2021-07-24 21:36 UTC, nscarcella requested changes

2021-07-30 23:46 UTC, AngeliMatias commented
Ya está pasada la implementación a Wollok, desarrollamos un poco más lo cambios en https://github.com/uqbar-project/wollok-language/pull/105

2021-07-31 00:47 UTC, nscarcella approved these changes
Listo. El CI falla porque le faltan los cambios en lang. Cuando mergeen lange hay que hacer un tag nuevo y actualizar el `wollokVersion` del package acá.

2021-08-02 20:41 UTC, PalumboN approved these changes
:+1:

2021-08-04 14:05 UTC, merged